import turtle
wn=turtle.Screen()
wn.bgcolor("WHITE")
alex=turtle.Turtle()
alex.color("BLACK")
alex.pensize(3)
alex.forward(150)
alex.left(90)
alex.forward(75)
alex.left(90)
alex.forward(150)
alex.left(90)
alex.forward(75)
wn.exitonclick()